name: Dan Willoughby
favicon: null
layout_spectrum: 0.47254474251531065
typography_spectrum: 0.8427148850169033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.01547869830392301
  lightness: 0.9623609366826713
  saturation: 0.14586141612380743
  rhythmicContrast: 0.5455346233211458
purpose: []
